name: Scrap Data

on:
  schedule:
    - cron: "0 1 * * *" # 6:30am IST
  workflow_dispatch:

jobs:
  run-scraper:
    uses: coronasafe/leaderboard/.github/workflows/scraper.yaml@reusable-scraper-workflow
    permissions:
      issues: read
      pull-requests: read
      contents: write
    secrets:
      SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
    with:
      slack-eod-channel: ${{ vars.SLACK_EOD_CHANNEL }}
