name: Slack EOD Reminder Bot

on:
  schedule:
    - cron: "30 13 * * *" # 7:00pm IST
  workflow_dispatch:

jobs:
  run-slack-eod-reminder:
    uses: coronasafe/leaderboard/.github/workflows/slack_eod_reminder.yaml@main
    if: github.ref == 'refs/heads/main'
    permissions:
      issues: read
      pull-requests: read
    secrets: inherit
